apiVersion: apps/v1
kind: Deployment
metadata:
  name: platformservice-deploy
 # labels:
  #  app: platformservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
      - name: platformservice
        image: hamzataoujouti/k8_platformservice:latest
        imagePullPolicy: Never
     #   ports:
      #  - containerPort: 80